/**
 * Infinite Marquee 1.0.0
 * Infinite Horizontal & Vertical Marquee animation based on CSS and controlled with JS
 *
 * Copyright 2023 Vahan Baghdasaryan
 *
 * Released under the MIT License
 *
 * Released on: October 21, 2023
 */


export default class InfiniteMarquee{constructor(e={}){this.element="string"==typeof e.element?[...document.querySelectorAll(e.element)]:e.element,this.direction=e.direction||"left",this.gap=e.gap||"0px",this.speed=e.speed||1e4,this.smoothEdges=e.smoothEdges||!1,this.fullContainer=e.fullContainer||!0,this.duplicateCount=e.duplicateCount||1,this.breakpointSize=e.breakpointSize||991.8,this.mobileSettings=e.mobileSettings||{},this.on={beforeInit:e.on&&e.on.beforeInit||null,afterInit:e.on&&e.on.afterInit||null},this.scrollType="top"===e.direction||"bottom"===e.direction?"vertical":"horizontal",this.init()}init(){if(("undefined"!=typeof window||"undefined"!=typeof document)&&(Array.isArray(this.element)?this.element.length>0:this.element)){if("function"==typeof this.on.beforeInit&&this.on.beforeInit(),Array.isArray(this.element))for(let e of this.element)this.configureChildNodes(e),this.configureAnimationOptions(e);else this.configureChildNodes(this.element),this.configureAnimationOptions(this.element);"function"==typeof this.on.afterInit&&this.on.afterInit()}}configureChildNodes(e){let t=document.createElement("div");for(t.classList.add(`${this.scrollType}-marquee-inner`);e.firstChild;)t.appendChild(e.firstChild);e.classList.add(`${this.scrollType}-marquee`),e.appendChild(t),this.duplicateOriginalNodes(t),this.duplicateContainer(e)}duplicateOriginalNodes(e){let t=e.children,i=[];for(let s=0;s<t.length;s++){let n=t[s],o=n.cloneNode(!0);o.setAttribute("aria-hidden",!0),i.push(o)}for(let l of i)e.appendChild(l)}duplicateContainer(e){let t=e.querySelector(`.${this.scrollType}-marquee-inner`),i=t.cloneNode(!0);i.setAttribute("aria-hidden",!0);let s=i.children;for(let n=0;n<s.length;n++)s[n].removeAttribute("aria-hidden");let o="vertical"===this.scrollType?this.duplicateCount+1:this.duplicateCount,l=Array.from({length:o},()=>i.cloneNode(!0));if(e.append(...l),"vertical"===this.scrollType){let r=e.clientHeight-t.clientHeight;e.style.setProperty("--_containerSize",`${r}px`)}}configureAnimationOptions(e){let t=window.matchMedia(`(max-width: ${this.breakpointSize}px)`),i=()=>{let i=this.mobileSettings.direction||this.direction,s="right"===this.direction||"bottom"===this.direction,n=t.matches?"right"===i||"bottom"===i?"reverse":"forwards":s?"reverse":"forwards",o=t.matches&&this.mobileSettings.speed||this.speed,l=t.matches&&this.mobileSettings.gap||this.gap;e.style.setProperty("--_speed",`${o}ms`),e.style.setProperty("--_gap",l),e.style.setProperty("--_direction",n),this.smoothEdges&&e.classList.add("smooth"),this.fullContainer&&e.classList.add("full")};i(),window.addEventListener("resize",i)}};
