/**
 * Infinite Marquee 1.0.0
 * Infinite Horizontal & Vertical Marquee animation based on CSS and controlled with JS
 *
 * Copyright 2023 Vahan Baghdasaryan
 *
 * Released under the MIT License
 *
 * Released on: October 21, 2023
 */


export default class InfiniteMarquee{constructor(e={}){this.element="string"==typeof e.element?[...document.querySelectorAll(e.element)]:e.element,this.direction=e.direction||"left",this.gap=e.gap||"0px",this.speed=e.speed||1e4,this.smoothEdges=e.smoothEdges||!1,this.fullContainer=e.fullContainer||!1,this.duplicateCount=e.duplicateCount||1,this.breakpointSize=e.breakpointSize||991.8,this.mobileSettings=e.mobileSettings||{},this.on={beforeInit:e.on&&e.on.beforeInit||null,afterInit:e.on&&e.on.afterInit||null},this.scrollType="top"===e.direction||"bottom"===e.direction?"vertical":"horizontal",this.init()}init(){if(("undefined"!=typeof window||"undefined"!=typeof document)&&(Array.isArray(this.element)?this.element.length>0:this.element)){if("function"==typeof this.on.beforeInit&&this.on.beforeInit(),Array.isArray(this.element))for(const e of this.element)this.configureChildNodes(e),this.configureAnimationOptions(e);else this.configureChildNodes(this.element),this.configureAnimationOptions(this.element);"function"==typeof this.on.afterInit&&this.on.afterInit()}}configureChildNodes(e){const t=document.createElement("div");for(t.classList.add(`${this.scrollType}-marquee-inner`);e.firstChild;)t.appendChild(e.firstChild);e.classList.add(`${this.scrollType}-marquee`),e.appendChild(t),this.duplicateOriginalNodes(t),this.duplicateContainer(e)}duplicateOriginalNodes(e){const t=e.children,i=[];for(let e=0;e<t.length;e++){const n=t[e].cloneNode(!0);n.setAttribute("aria-hidden",!0),i.push(n)}for(const t of i)e.appendChild(t)}duplicateContainer(e){const t=e.querySelector(`.${this.scrollType}-marquee-inner`),i=t.cloneNode(!0);i.setAttribute("aria-hidden",!0);const n=i.children;for(let e=0;e<n.length;e++)n[e].removeAttribute("aria-hidden");const s="vertical"===this.scrollType?this.duplicateCount+1:this.duplicateCount,o=Array.from({length:s},(()=>i.cloneNode(!0)));if(e.append(...o),"vertical"===this.scrollType){const i=e.clientHeight-t.clientHeight;e.style.setProperty("--_containerSize",`${i}px`)}}configureAnimationOptions(e){const t=window.matchMedia(`(max-width: ${this.breakpointSize}px)`),i=()=>{const i=this.mobileSettings.direction||this.direction,n="right"===i||"bottom"===i,s="right"===this.direction||"bottom"===this.direction,o=t.matches?n?"reverse":"forwards":s?"reverse":"forwards",r=t.matches&&this.mobileSettings.speed||this.speed,l=t.matches&&this.mobileSettings.gap||this.gap;e.style.setProperty("--_speed",`${r}ms`),e.style.setProperty("--_gap",l),e.style.setProperty("--_direction",o),this.smoothEdges&&e.classList.add("smooth"),this.fullContainer&&e.classList.add("full")};i(),window.addEventListener("resize",i)}}
